#include <math.h>
#include <splexer.h>
#include <sptl.h>
#include <errno.h>

#define TODO_LINE 1337

static Sp_String_Builder generated = {0};

struct Schwasm {
    Sp_Lexer lexer;
    struct {
        size_t idx;
        bool busy;
    } lexer_attr;

    uint16_t addr; // GCPU uses a 4K ROM, only requires 12-bit wide address; 16-bits is more than enough
};

static inline const Sp_Lexer_Token *schwasm_get_token(struct Schwasm *schwasm) {
    if (schwasm->lexer_attr.idx >= schwasm->lexer.tokens.count) {
        return NULL;
    }

    sp_log(SP_INFO, "%s", schwasm->lexer.tokens.data[schwasm->lexer_attr.idx].sb.data);

    return &schwasm->lexer.tokens.data[schwasm->lexer_attr.idx];
}

static inline const Sp_Lexer_Token *schwasm_next_token(struct Schwasm *schwasm) {
    ++schwasm->lexer_attr.idx;
    return schwasm_get_token(schwasm);
}

enum Schwasm_Value_Type {
    SCHWASM_VALUE_ERROR,
    SCHWASM_VALUE_HEX,
    SCHWASM_VALUE_DECIMAL,
};
static inline enum Schwasm_Value_Type schwasm_expect_value(struct Schwasm *schwasm) {
    const Sp_Lexer_Token *token = schwasm_next_token(schwasm);

    if (!token || token->type == TOK_Newline) {
        sp_log(SP_ERROR, "Line %d: Expected value", TODO_LINE);
        return SCHWASM_VALUE_ERROR;
    }

    if (strcmp("$", token->sb.data) == 0) {
        token = schwasm_next_token(schwasm);

        if (!token) {
            sp_log(SP_ERROR, "Line %d: Unexpected EOF", TODO_LINE);
            return SCHWASM_VALUE_ERROR;
        }

        if (token->type == TOK_Newline) {
            sp_log(SP_ERROR, "Line %d: Expected hexadecimal value after $", TODO_LINE);
            return SCHWASM_VALUE_ERROR;
        }

        if (token->type != TOK_IntLiteral && token->type != TOK_ID) {
            sp_log(SP_ERROR, "Line %d: Unexpected token after $", TODO_LINE);
            return SCHWASM_VALUE_ERROR;
        }

        return SCHWASM_VALUE_HEX;
    } else if (token->type == TOK_IntLiteral) {
        return SCHWASM_VALUE_DECIMAL;
    } else {
        sp_log(SP_ERROR, "Line %d: Unexpected value", TODO_LINE);
        return SCHWASM_VALUE_ERROR;
    }
}

enum GCPU_REG {
    GCPU_REGA,
    GCPU_REGB,
    GCPU_REGX,
    GCPU_REGY
};

int ld_imm(struct Schwasm *schwasm, enum GCPU_REG reg) {
        switch (reg) {
            case GCPU_REGA:
                sp_sb_appendf(&generated, "\t%04X : 02;\n", schwasm->addr++);
                break;
            case GCPU_REGB:
                sp_sb_appendf(&generated, "\t%04X : 03;\n", schwasm->addr++);
                break;
            case GCPU_REGX:
                sp_sb_appendf(&generated, "\t%04X : 08;\n", schwasm->addr++);
                break;
            case GCPU_REGY:
                sp_sb_appendf(&generated, "\t%04X : 09;\n", schwasm->addr++);
                break;
        }

    switch (schwasm_expect_value(schwasm)) {
        case SCHWASM_VALUE_HEX:
            if (schwasm_get_token(schwasm)->sb.count > 2) {
                sp_log(SP_ERROR, "Line %d: Register does not support loading %d-bit integers", TODO_LINE, (int) powl(2, schwasm_get_token(schwasm)->sb.count));
                return 1;
            }

            errno = 0;
            int value = (int) strtol(schwasm_get_token(schwasm)->sb.data, NULL, 16);

            if (errno != 0) {
                sp_log(SP_ERROR, "Line %d: Error parsing hexadecimal value", TODO_LINE);
                return 1;
            }

            sp_sb_appendf(&generated, "\t%04X : %02X;\n", schwasm->addr++, value);
            break;
        case SCHWASM_VALUE_DECIMAL:
            sp_sb_appendf(&generated, "\t%04X : %02X;\n", schwasm->addr++, (int) schwasm_get_token(schwasm)->int_lit.value);
            break;
        case SCHWASM_VALUE_ERROR:
            return 1;
    }

    return 0;
}

int ld_reg(struct Schwasm *schwasm) {
    (void) schwasm;
    return 1;
}

int ld(struct Schwasm *schwasm, enum GCPU_REG reg) {
    const Sp_Lexer_Token *token = schwasm_next_token(schwasm);

    if (!token) {
        sp_log(SP_ERROR, "Unexpected rhs");
        return 1;
    }

    if (token->type == TOK_Pound) {
        return ld_imm(schwasm, reg);
    } else {
        return ld_reg(schwasm);
    }
}

int main(int argc, char **argv) {
    if (argc == 1) {
        sp_log(SP_ERROR, "Not enough arguments (expected a filename)");
        return 1;
    }
    if (argc > 2) {
        sp_log(SP_ERROR, "Too many arguments (expected 1, got %d)", argc - 1);
        return 1;
    }

    struct Schwasm schwasm = {0};

    if (splexer_init(&schwasm.lexer, argv[1]) != 0) {
        sp_log(SP_ERROR, "Unable to open file: \"%s\"", argv[1]);
        return 1;
    }

    while (schwasm.lexer.state != SPLEXER_TERMINATE) {
        splexer_tokenize(&schwasm.lexer);
    }

    sp_sb_appendf(&generated, "-- \tGenerated by Schwasm.\t --\n");
    sp_sb_appendf(&generated, "DEPTH = 4096;\n");
    sp_sb_appendf(&generated, "WIDTH = 8;\n\n");

    sp_sb_appendf(&generated, "ADDRESS_RADIX = HEX;\n");
    sp_sb_appendf(&generated, "DATA_RADIX = HEX;\n\n");

    sp_sb_appendf(&generated, "CONTENT\nBEGIN\n");

    const Sp_Lexer_Token *token = schwasm_get_token(&schwasm);

    if (!token) {
        sp_log(SP_ERROR, "Line %d: Unexpected initial token", TODO_LINE);
        return 1;
    }

    do {
        if (token->type == TOK_Newline) {
            schwasm.lexer_attr.busy = false;
            continue;
        }

        if (schwasm.lexer_attr.busy) { // some token after a completed instruction
            sp_log(SP_ERROR, "Line %d: Trailing tokens after instruction", TODO_LINE);
            return 1;
        }

        if (token->type != TOK_ID) {
            sp_log(SP_ERROR,
                   "Line %d: Failed to parse unknown symbol \"%s\"",
                   TODO_LINE,
                   SPLEXER_TOKENS_LITERAL[token->type]);
            return 1;
        }

        schwasm.lexer_attr.busy = true;

        if (strcmp("ORG", token->sb.data) == 0) {
        } else if (strcmp("TAB", token->sb.data) == 0) {
            sp_sb_appendf(&generated, "%04X : 00", schwasm.addr++);
        } else if (strcmp("TBA", token->sb.data) == 0) {
            sp_sb_appendf(&generated, "%04X : 01", schwasm.addr++);
        } else if (strcmp("LDAA", token->sb.data) == 0) {
            if (ld(&schwasm, GCPU_REGA) != 0) {
                sp_log(SP_ERROR, "Line %d: Failed to parse LDAA", TODO_LINE);
                return 1;
            }
        } else if (strcmp("LDAB", token->sb.data) == 0) {
            if (ld(&schwasm, GCPU_REGB) != 0) {
                sp_log(SP_ERROR, "Line %d: Failed to parse LDAB", TODO_LINE);
                return 1;
            }
        } else {
            sp_log(SP_ERROR, "Line %d: Failed to parse unknown instruction \"%s\"", TODO_LINE, token->sb.data);
            return 1;
        }
    } while ((token = schwasm_next_token(&schwasm)));

    sp_sb_appendf(&generated, "END;\n");
    printf("%s", generated.data);

    sp_da_free(&generated);
    splexer_destroy(&schwasm.lexer);

    return 0;
}
