#include "schwasm.h"

static Sp_String_Builder rom_sb = {0};
static Sp_String_Builder ram_sb = {0};

static const char *input_path = NULL;
static Sp_String_Builder output_dir = {0};
enum Output_Mode {
    OUTPUT_NIL,
    OUTPUT_FILE,
    OUTPUT_PRINT
};
static enum Output_Mode output_mode = OUTPUT_NIL;

void cleanup() {
    sp_da_free(&rom_sb);
    sp_da_free(&ram_sb);
    sp_da_free(&output_dir);
}

static inline void gen_boilerplate(Sp_String_Builder *sb, const int size, const char *watermark) {
    if (watermark) {
        sp_sb_append(sb, "-- \t");
        sp_sb_append(sb, watermark);
        sp_sb_append(sb, "\t--\n");
    }

    sp_sb_appendf(sb, "DEPTH = %d;\n", size);
    sp_sb_append(sb, "WIDTH = 8;\n\n");

    sp_sb_append(sb, "ADDRESS_RADIX = HEX;\n");
    sp_sb_append(sb, "DATA_RADIX = HEX;\n\n");

    sp_sb_append(sb, "CONTENT\nBEGIN\n\n");
}

int main(int argc, char **argv) {
    atexit(cleanup);

    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "-D") == 0) {
            if (i + 1 >= argc) {
                sp_die(1, "-D: expected a path\n");
            }
            if (output_mode == OUTPUT_PRINT) {
                sp_die(1, "-D: flag conflicts with -p\n");
            }
            output_mode = OUTPUT_FILE;
            sp_da_clear(&output_dir);
            sp_sb_append(&output_dir, argv[++i]);
        } else if (strcmp(argv[i], "-p") == 0) {
            if (output_mode == OUTPUT_FILE) {
                sp_die(1, "-p: flag conflicts with -D\n");
            }

            output_mode = OUTPUT_PRINT;
        } else {
            if (input_path) {
                sp_die(1, "Unknown trailing argument \"%s\"\n", argv[i]);
            }

            input_path = argv[i];
        }
    }

    if (!input_path) {
        sp_die(1, "Usage: `schwasm file.asm`\n");
    }

    struct Schwasm schwasm = schwasm_init(input_path);
    if (splexer_init(&schwasm.lexer, input_path) != 0) {
        sp_die(1, "Unable to open file: \"%s\": %s\n", input_path, strerror(errno));
    }

    schwasm_generate_ir(&schwasm);
    Schwasm_Nodes* nodes = NULL;

    if (schwasm.addr_unsorted) {
        nodes = malloc(sizeof(Schwasm_Nodes));
        sp_da_reserve(nodes, schwasm.nodes.count);

        // pigeonhole sort
        uint16_t ordered_idx[ADDR_LEN];
        memset(ordered_idx, 0xFF, ADDR_LEN * sizeof(uint16_t)); // use 0xFFFF as sentinel value since valid addresses 0x0000 -> 0x1FFF (change if this ever changes)

        for (uint16_t i = 0; i < schwasm.nodes.count; ++i) {
            uint16_t a = schwasm.nodes.data[i].addr;
            assert(ordered_idx[a] == 0xFFFF); // this should be enforced by uniqueness invariant

            ordered_idx[a] = i;
        }

        for (uint16_t i = 0; i < ADDR_LEN; ++i) {
            if (ordered_idx[i] == 0xFFFF) continue;
            sp_da_push(nodes, schwasm.nodes.data[ordered_idx[i]]);
        }
    } else {
        nodes = &schwasm.nodes;
    }

    gen_boilerplate(&rom_sb, 4096, "rom.mif : Generated by Schwasm");
    gen_boilerplate(&ram_sb, 4096, "ram.mif : Generated by Schwasm");

    // TODO: better way of generating both rom and ram
    uint16_t rom_next_addr = 0x0000;
    uint16_t ram_next_addr = 0x0000;
    uint16_t write_addr = 0x0000;
    const struct Schwasm_Node *node = NULL;
    Sp_String_Builder *sb = NULL;
    uint16_t *next_addr = NULL;
    for (size_t i = 0; i < nodes->count; ++i) {
        node = &nodes->data[i];

        if (node->addr >= 0x1000) {
            write_addr = node->addr - 0x1000;
            sb = &ram_sb;
            next_addr = &ram_next_addr;
        } else {
            write_addr = node->addr;
            sb = &rom_sb;
            next_addr = &rom_next_addr;
        }

        // "calloc" unspecified memory regions
        if (write_addr > *next_addr) {
            sp_sb_appendf(sb, "[%04X..%04X]\t:\t%02X;\n\n", *next_addr, write_addr - 1, 0x00);
        }

        *next_addr = write_addr + SCHWASM_OP_COUNT[node->op];

        switch (SCHWASM_OP_COUNT[node->op]) {
            case 0:
                sp_sb_appendf(sb, "[%04X..%04X]\t:\t%02X;\n\n", write_addr, write_addr + node->dword - 1, 0x00); // allocate node.dword bytes
                *next_addr = write_addr + node->dword;
                break;
            case 1:
                if (node->op == SCHWASM_AD_DC) {
                    sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n\n", write_addr, node->word);
                } else {
                    sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n\n", write_addr, node->op);
                }
                break;
            case 2:
                sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n", write_addr, node->op);
                sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n\n", write_addr + 1, node->word);
                break;
            case 3:
                sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n", write_addr, node->op);
                sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n", write_addr + 1, node->lword);
                sp_sb_appendf(sb, "%04X\t\t:\t%02X;\n\n", write_addr + 2, node->hword);
                break;
            default:
                sp_unreachable();
        }
    }

    sp_da_free(nodes);
    schwasm_destroy(&schwasm);

    // "calloc" until end
    if (0x0FFF > rom_next_addr) {
        sp_sb_appendf(&rom_sb, "[%04X..%04X]\t:\t%02X;\n", rom_next_addr, 0x0FFF, 0x00);
    }
    if (0x0FFF > ram_next_addr) {
        sp_sb_appendf(&ram_sb, "[%04X..%04X]\t:\t%02X;\n", ram_next_addr, 0x0FFF, 0x00);
    }

    sp_sb_append(&rom_sb, "END;");
    sp_sb_append(&ram_sb, "END;");

    FILE *rom;
    FILE *ram;
    Sp_String_Builder rom_path = {0};
    Sp_String_Builder ram_path = {0};
    switch (output_mode) {
        case OUTPUT_NIL:
            sp_sb_append(&output_dir, ".");
        case OUTPUT_FILE:
            sp_sb_append(&rom_path, output_dir.data);
            sp_sb_append(&rom_path, "/rom.mif");

            sp_sb_append(&ram_path, output_dir.data);
            sp_sb_append(&ram_path, "/ram.mif");

            rom = fopen(rom_path.data, "w");

            if (!rom) {
                sp_die(1, "Unable to write to file \"%s\": %s\n", rom_path.data, strerror(errno));
            }

            errno = 0;
            if (rom_sb.count > fwrite(rom_sb.data, sizeof(char), rom_sb.count, rom)) {
                fclose(rom);
                sp_die(1, "ROM fwrite(): %s", strerror(errno));
            }

            errno = 0;
            if (fclose(rom) != 0) {
                sp_die(1, "ROM fclose(): %s", strerror(errno));
            }

            ram = fopen(ram_path.data, "w");
            if (!ram) {
                sp_die(1, "Unable to write to file \"%s\": %s\n", ram_path.data, strerror(errno));
            }

            errno = 0;
            if (ram_sb.count > fwrite(ram_sb.data, sizeof(char), ram_sb.count, ram)) {
                fclose(ram);
                sp_die(1, "RAM fwrite(): %s", strerror(errno));
            }

            errno = 0;
            if (fclose(ram) != 0) {
                sp_die(1, "RAM fclose(): %s", strerror(errno));
            }

            sp_da_free(&rom_path);
            sp_da_free(&ram_path);
            break;
        case OUTPUT_PRINT:
            fputs(rom_sb.data, stdout);
            fputc('\n', stdout);
            fputs(ram_sb.data, stdout);
            fputc('\n', stdout);
            break;
    }

    return 0;
}
