#include "schwasm.h"

#include <sptl.h>

FILE *rom = NULL;
FILE *ram = NULL;

static const char *input_path = NULL;
static Sp_String_Builder output_dir = {0};

enum Output_Mode { OUTPUT_NIL, OUTPUT_FILE, OUTPUT_PRINT };
static enum Output_Mode output_mode = OUTPUT_NIL;

void cleanup() { sp_da_free(&output_dir); }

static inline void gen_boilerplate(FILE *f, const char *watermark) {
    if (watermark) {
        fputs("-- \t", f);
        fputs(watermark, f);
        fputs("\t--\n", f);
    }

    fputs("DEPTH = 4096;\n", f);
    fputs("WIDTH = 8;\n\n", f);

    fputs("ADDRESS_RADIX = HEX;\n", f);
    fputs("DATA_RADIX = HEX;\n\n", f);

    fputs("CONTENT\nBEGIN\n\n", f);
}

int main(int argc, char **argv) {
    atexit(cleanup);

    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "-D") == 0) {
            if (i + 1 >= argc) {
                sp_die(1, "-D: expected a path\n");
            }
            if (output_mode == OUTPUT_PRINT) {
                sp_die(1, "-D: flag conflicts with -p\n");
            }
            output_mode = OUTPUT_FILE;
            sp_da_clear(&output_dir);
            sp_sb_append(&output_dir, argv[++i]);
        } else if (strcmp(argv[i], "-p") == 0) {
            if (output_mode == OUTPUT_FILE) {
                sp_die(1, "-p: flag conflicts with -D\n");
            }

            output_mode = OUTPUT_PRINT;
        } else {
            if (input_path) {
                sp_die(1, "Unknown trailing argument \"%s\"\n", argv[i]);
            }

            input_path = argv[i];
        }
    }

    if (!input_path) {
        sp_die(1, "Usage: `schwasm file.asm`\n");
    }

    struct Schwasm schwasm = schwasm_init(input_path);
    if (splexer_init(&schwasm.lexer, input_path) != 0) {
        sp_die(1,
               "Unable to open file: \"%s\": %s\n",
               input_path,
               strerror(errno));
    }

    {
        Sp_String_Builder rom_path = {0};
        Sp_String_Builder ram_path = {0};
        switch (output_mode) {
            case OUTPUT_NIL: sp_sb_append(&output_dir, ".");
            case OUTPUT_FILE:
                sp_sb_append(&rom_path, output_dir.data);
                sp_sb_append(&rom_path, "/rom.mif");

                sp_sb_append(&ram_path, output_dir.data);
                sp_sb_append(&ram_path, "/ram.mif");

                rom = fopen(rom_path.data, "wb");

                if (!rom) {
                    sp_die(1,
                           "Unable to write to file \"%s\": %s\n",
                           rom_path.data,
                           strerror(errno));
                }

                ram = fopen(ram_path.data, "wb");
                if (!ram) {
                    sp_die(1,
                           "Unable to write to file \"%s\": %s\n",
                           ram_path.data,
                           strerror(errno));
                }

                sp_da_free(&rom_path);
                sp_da_free(&ram_path);
                break;
            case OUTPUT_PRINT:
                rom = stdout;
                ram = tmpfile();

                if (!ram) {
                    sp_die(1, "tmpfile()\n");
                }
                break;
        }
    }

    schwasm_generate_ir(&schwasm);
    Schwasm_Nodes *nodes = NULL;

    if (schwasm.addr_unsorted) {
        nodes = malloc(sizeof(Schwasm_Nodes));
        sp_da_reserve(nodes, schwasm.nodes.count);

        // pigeonhole sort
        uint16_t ordered_idx[ADDR_LEN];
        memset(ordered_idx,
               0xFF,
               ADDR_LEN *
                   sizeof(uint16_t)); // use 0xFFFF as sentinel value since
                                      // valid addresses 0x0000 -> 0x1FFF
                                      // (change if this ever changes)

        for (uint16_t i = 0; i < schwasm.nodes.count; ++i) {
            uint16_t a = schwasm.nodes.data[i].addr;
            assert(ordered_idx[a] ==
                   0xFFFF); // this should be enforced by uniqueness invariant

            ordered_idx[a] = i;
        }

        for (uint16_t i = 0; i < ADDR_LEN; ++i) {
            if (ordered_idx[i] == 0xFFFF) continue;
            sp_da_push(nodes, schwasm.nodes.data[ordered_idx[i]]);
        }
    } else {
        nodes = &schwasm.nodes;
    }

    // TODO: hardcoded to 4096 for both for now
    gen_boilerplate(rom, "rom.mif : Generated by Schwasm");
    gen_boilerplate(ram, "ram.mif : Generated by Schwasm");

    // TODO: better way of generating both rom and ram
    Sp_String_Builder smart_buf = {0};
    sp_da_reserve(&smart_buf, 2048);

    uint16_t rom_next_addr = 0x0000;
    uint16_t ram_next_addr = 0x0000;
    uint16_t write_addr = 0x0000;
    const struct Schwasm_Node *node = NULL;
    FILE *f = NULL;
    uint16_t *next_addr = NULL;

    for (size_t i = 0; i < nodes->count; ++i) {
        node = &nodes->data[i];

        if (node->addr >= 0x1000) {
            write_addr = node->addr - 0x1000;
            f = ram;
            next_addr = &ram_next_addr;
        } else {
            write_addr = node->addr;
            f = rom;
            next_addr = &rom_next_addr;
        }

        // "calloc" unspecified memory regions
        if (write_addr > *next_addr) {
            sp_sb_append_c(&smart_buf, '[');
            sp_sb_append_hex_ex(&smart_buf, *next_addr, 0, 4);
            sp_sb_append(&smart_buf, "..");
            sp_sb_append_hex_ex(&smart_buf, write_addr - 1, 0, 4);
            sp_sb_append(&smart_buf, "]\t:\t00;\n\n");

            fputs(smart_buf.data, f);
            sp_da_clear(&smart_buf);
        }

        *next_addr = write_addr + SCHWASM_OP_COUNT[node->op];

        switch (SCHWASM_OP_COUNT[node->op]) {
            case 0:
                sp_sb_append_c(&smart_buf, '[');
                sp_sb_append_hex_ex(&smart_buf, write_addr, 0, 4);
                sp_sb_append(&smart_buf, "..");
                sp_sb_append_hex_ex(&smart_buf, write_addr + node->dword - 1, 0, 4);
                sp_sb_append(&smart_buf, "]\t:\t00;\n\n");

                fputs(smart_buf.data, f);
                sp_da_clear(&smart_buf);

                *next_addr = write_addr + node->dword;
                break;
            case 1:
                sp_sb_append_hex_ex(&smart_buf, write_addr, 0, 4);
                sp_sb_append(&smart_buf, "\t\t:\t");

                if (node->op == SCHWASM_AD_DC) {
                    sp_sb_append_hex_ex(&smart_buf, node->word, 0, 2);
                } else {
                    sp_sb_append_hex_ex(&smart_buf, node->op, 0, 2);
                }

                sp_sb_append(&smart_buf, ";\n\n");

                fputs(smart_buf.data, f);
                sp_da_clear(&smart_buf);
                break;
            case 2:
                sp_sb_append_hex_ex(&smart_buf, write_addr, 0, 4);
                sp_sb_append(&smart_buf, "\t\t:\t");
                sp_sb_append_hex_ex(&smart_buf, node->op, 0, 2);
                sp_sb_append(&smart_buf, ";\n");

                sp_sb_append_hex_ex(&smart_buf, write_addr + 1, 0, 4);
                sp_sb_append(&smart_buf, "\t\t:\t");
                sp_sb_append_hex_ex(&smart_buf, node->word, 0, 2);
                sp_sb_append(&smart_buf, ";\n\n");

                fputs(smart_buf.data, f);
                sp_da_clear(&smart_buf);
                break;
            case 3:
                sp_sb_append_hex_ex(&smart_buf, write_addr, 0, 4);
                sp_sb_append(&smart_buf, "\t\t:\t");
                sp_sb_append_hex_ex(&smart_buf, node->op, 0, 2);
                sp_sb_append(&smart_buf, ";\n");

                sp_sb_append_hex_ex(&smart_buf, write_addr + 1, 0, 4);
                sp_sb_append(&smart_buf, "\t\t:\t");
                sp_sb_append_hex_ex(&smart_buf, node->lword, 0, 2);
                sp_sb_append(&smart_buf, ";\n");

                sp_sb_append_hex_ex(&smart_buf, write_addr + 2, 0, 4);
                sp_sb_append(&smart_buf, "\t\t:\t");
                sp_sb_append_hex_ex(&smart_buf, node->hword, 0, 2);
                sp_sb_append(&smart_buf, ";\n\n");

                fputs(smart_buf.data, f);
                sp_da_clear(&smart_buf);
                break;
            default: sp_unreachable();
        }
    }

    sp_da_free(nodes);
    schwasm_destroy(&schwasm);

    // "calloc" until end
    if (0x0FFF >= rom_next_addr) {
        sp_sb_append_c(&smart_buf, '[');
        sp_sb_append_hex_ex(&smart_buf, rom_next_addr, 0, 4);
        sp_sb_append(&smart_buf, "..0FFF]\t:\t00;\n\n");

        fputs(smart_buf.data, rom);
        sp_da_clear(&smart_buf);
    }
    if (0x0FFF >= ram_next_addr) {
        sp_sb_append_c(&smart_buf, '[');
        sp_sb_append_hex_ex(&smart_buf, ram_next_addr, 0, 4);
        sp_sb_append(&smart_buf, "..0FFF]\t:\t00;\n\n");

        fputs(smart_buf.data, ram);
        sp_da_clear(&smart_buf);
    }

    fputs("END;\n", rom);
    fputs("END;\n", ram);
    sp_da_free(&smart_buf);

    {
        char buf[1024];
        switch (output_mode) {
            case OUTPUT_NIL:
            case OUTPUT_FILE:
                fclose(rom);
                fclose(ram);
                rom = NULL;
                ram = NULL;
                break;
            case OUTPUT_PRINT:
                rewind(ram);

                size_t bytes;
                while ((bytes = fread(buf, 1, sizeof(buf), ram)) > 0) {
                    fwrite(buf, 1, bytes, stdout);
                }

                fclose(ram);
                ram = NULL;
                break;
        }
    }

    return 0;
}
