#include "schwasm.h"

static Sp_String_Builder generated = {0};

static const char *input_path = NULL;
static Sp_String_Builder output_path = {0};
enum Output_Mode {
    OUTPUT_NIL,
    OUTPUT_FILE,
    OUTPUT_PRINT
};
static enum Output_Mode output_mode = OUTPUT_NIL;

void cleanup() {
    sp_da_free(&generated);
    sp_da_free(&output_path);
}

int main(int argc, char **argv) {
    atexit(cleanup);

    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "-D") == 0) {
            if (i + 1 >= argc) {
                sp_die(1, "-D: expected a path\n");
            }
            if (output_mode == OUTPUT_PRINT) {
                sp_die(1, "-D: flag conflicts with -p\n");
            }
            output_mode = OUTPUT_FILE;
            sp_da_clear(&output_path);
            sp_sb_appendf(&output_path, "%s", argv[++i]);
        } else if (strcmp(argv[i], "-p") == 0) {
            if (output_mode == OUTPUT_FILE) {
                sp_die(1, "-p: flag conflicts with -D\n");
            }

            output_mode = OUTPUT_PRINT;
        } else {
            if (input_path) {
                sp_die(1, "Unknown trailing argument \"%s\"\n", argv[i]);
            }

            input_path = argv[i];
        }
    }

    if (!input_path) {
        sp_die(1, "Usage: `schwasm file.asm`\n");
    }

    struct Schwasm schwasm = schwasm_init(input_path);
    if (splexer_init(&schwasm.lexer, input_path) != 0) {
        sp_die(1, "Unable to open file: \"%s\": %s\n", input_path, strerror(errno));
    }

    Schwasm_Nodes nodes = schwasm_generate_ir(&schwasm);
    schwasm_destroy(&schwasm);

    sp_sb_appendf(&generated, "-- \tGenerated by Schwasm.\t --\n");
    sp_sb_appendf(&generated, "DEPTH = %d;\n", ROM_SIZE);
    sp_sb_appendf(&generated, "WIDTH = 8;\n\n");

    sp_sb_appendf(&generated, "ADDRESS_RADIX = HEX;\n");
    sp_sb_appendf(&generated, "DATA_RADIX = HEX;\n\n");

    sp_sb_appendf(&generated, "CONTENT\nBEGIN\n\n");


    uint16_t next_addr = 0x0000;
    const struct Schwasm_Node *node = NULL;
    for (size_t i = 0; i < nodes.count; ++i) {
        node = &nodes.data[i];

        // "calloc" unspecified memory regions
        if (node->addr > next_addr) {
            sp_sb_appendf(&generated, "[%04X..%04X]\t:\t%02X;\n\n", next_addr, node->addr - 1, 0x00);
        }

        next_addr = node->addr + SCHWASM_OP_COUNT[node->op];

        switch (SCHWASM_OP_COUNT[node->op]) {
            case 0:
                sp_sb_appendf(&generated, "[%04X..%04X]\t:\t%02X;\n\n", node->addr, node->addr + node->dword - 1, 0x00); // allocate node.dword bytes
                next_addr = node->addr + node->dword;
                break;
            case 1:
                if (node->op == SCHWASM_AD_DC) {
                    sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n\n", node->addr, node->word);
                } else {
                    sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n\n", node->addr, node->op);
                }
                break;
            case 2:
                sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n", node->addr, node->op);
                sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n\n", node->addr + 1, node->word);
                break;
            case 3:
                sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n", node->addr, node->op);
                sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n", node->addr + 1, node->lword);
                sp_sb_appendf(&generated, "%04X\t\t:\t%02X;\n\n", node->addr + 2, node->hword);
                break;
            default:
                sp_unreachable();
        }
    }

    // "calloc" until end
    if (0x0FFF > next_addr) {
        sp_sb_appendf(&generated, "[%04X..%04X]\t:\t%02X;\n", next_addr, 0x0FFF, 0x00);
    }

    sp_sb_appendf(&generated, "END;\n");

    FILE *output;
    switch (output_mode) {
        case OUTPUT_NIL:
            sp_sb_appendf(&output_path, ".");
        case OUTPUT_FILE:
            sp_sb_appendf(&output_path, "/rom.mif");
            output = fopen(output_path.data, "w");

            if (!output) {
                sp_die(1, "Unable to write to file \"%s\": %s\n", output_path.data, strerror(errno));
            }

            errno = 0;
            if (generated.count > fwrite(generated.data, sizeof(char), generated.count, output)) {
                fclose(output);
                sp_die(1, "fwrite(): %s", strerror(errno));
            }

            errno = 0;
            if (fclose(output) != 0) {
                sp_die(1, "fclose(): %s", strerror(errno));
            }
            break;
        case OUTPUT_PRINT:
            printf("%s", generated.data);
            break;
    }

    return 0;
}
